[build]
  command = "pnpm -C apps/web build"
  publish = "apps/web/dist"

[functions]
  node_bundler = "esbuild"
  included_files = ["packages/**/*", "functions/**/*"]

[[edge_functions]]
  path = "/.netlify/functions/*"
  function = "security"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[scheduled.functions]]
  name = "retentionSweep"
  cron = "0 6 * * *" # daily at 06:00 UTC
