[build]
  command = "pnpm install --no-frozen-lockfile && pnpm -C apps/web build"
  publish = "apps/web/dist"

[build.environment]
  # Disable frozen lockfile for pnpm's automatic install phase
  PNPM_FLAGS = "--no-frozen-lockfile"
  # Enable pnpm explicitly
  NPM_FLAGS = "--version"

[functions]
  node_bundler = "esbuild"
  included_files = ["packages/**/*", "functions/**/*"]
  directory = "functions"

[[edge_functions]]
  path = "/.netlify/functions/*"
  function = "security"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[scheduled.functions]]
  name = "retentionSweep"
  cron = "0 6 * * *" # daily at 06:00 UTC
