import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function ExportStage({ presets, onTogglePreset, onStartRender, renderStatus, isRendering, downloads, onDeleteExport, onDeleteAsset }) {
    const labelFor = (presetId) => presets.find((p) => p.id === presetId)?.label || presetId;
    return (_jsxs("section", { className: "space-y-6", children: [_jsxs("header", { className: "flex flex-wrap items-start justify-between gap-4", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-xl font-semibold text-white", children: "Export Suite" }), _jsx("p", { className: "text-sm text-slate-400", children: "Encode multiple aspect ratios in parallel. We deliver signed URLs ready for Instagram, TikTok, YouTube, and Hudl." })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("button", { type: "button", onClick: onStartRender, disabled: isRendering, className: "rounded-full border border-emerald-400/50 bg-emerald-400/10 px-4 py-1.5 text-sm font-semibold text-emerald-100 transition hover:bg-emerald-400/20 disabled:opacity-40", children: isRendering ? 'Rendering...' : 'Render Hype Video' }), onDeleteAsset && (_jsx("button", { type: "button", onClick: () => {
                                    if (confirm('Delete asset and clear this session? This cannot be undone.'))
                                        onDeleteAsset();
                                }, className: "rounded-full border border-red-400/50 bg-red-500/10 px-4 py-1.5 text-xs font-semibold uppercase tracking-[0.14em] text-red-100 transition hover:bg-red-500/20", children: "Delete Asset" }))] })] }), _jsx("div", { className: "grid gap-4 sm:grid-cols-2", children: presets.map((preset) => (_jsxs("label", { className: `flex cursor-pointer flex-col gap-3 rounded-3xl border p-4 transition ${preset.enabled
                        ? 'border-indigo-400/40 bg-indigo-500/10 shadow-lg shadow-indigo-500/10'
                        : 'border-white/10 bg-slate-900/60 hover:border-indigo-400/40 hover:bg-indigo-500/10'}`, children: [_jsxs("div", { className: "flex items-start justify-between gap-3", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-semibold text-white", children: preset.label }), _jsxs("p", { className: "text-xs text-slate-400", children: [preset.aspect, " / ", preset.resolution] })] }), _jsx("input", { type: "checkbox", className: "mt-1 h-5 w-5 cursor-pointer rounded border border-white/20 bg-slate-900 text-indigo-400 accent-indigo-500", checked: preset.enabled, onChange: () => onTogglePreset(preset.id) })] }), _jsxs("dl", { className: "grid grid-cols-2 gap-2 text-xs uppercase tracking-[0.14em] text-slate-400", children: [_jsx(Stat, { label: "Aspect", value: preset.aspect }), _jsx(Stat, { label: "Resolution", value: preset.resolution }), _jsx(Stat, { label: "Bitrate", value: preset.bitrate }), _jsx(Stat, { label: "Codec", value: preset.container })] }), _jsx("div", { className: "h-1.5 w-full overflow-hidden rounded-full bg-slate-800", children: _jsx("div", { className: "h-full rounded-full bg-gradient-to-r from-indigo-400 via-sky-400 to-emerald-400 transition-[width]", style: { width: `${preset.progress}%` } }) })] }, preset.id))) }), renderStatus && (_jsx("div", { className: "rounded-3xl border border-white/10 bg-slate-900/60 p-4 text-sm text-slate-300", children: renderStatus })), downloads && downloads.length > 0 && (_jsxs("div", { className: "rounded-3xl border border-emerald-400/20 bg-emerald-500/5 p-4", children: [_jsx("p", { className: "text-xs uppercase tracking-[0.16em] text-emerald-200/80", children: "Downloads" }), _jsx("ul", { className: "mt-3 space-y-2 text-sm", children: downloads.map((d) => (_jsxs("li", { className: "flex items-center justify-between rounded-xl border border-white/10 bg-slate-950/60 p-3", children: [_jsxs("div", { children: [_jsx("p", { className: "font-medium text-white", children: labelFor(d.presetId) }), _jsxs("p", { className: "text-xs text-slate-400", children: ["Expires ", new Date(d.expiresAt).toLocaleString()] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("a", { href: d.url, target: "_blank", rel: "noreferrer", className: "rounded-full border border-emerald-400/40 bg-emerald-400/10 px-3 py-1 text-xs font-semibold text-emerald-100 hover:bg-emerald-400/20", children: "Download" }), onDeleteExport && (_jsx("button", { type: "button", onClick: () => {
                                                if (confirm(`Delete export ${labelFor(d.presetId)}?`))
                                                    onDeleteExport(d.presetId);
                                            }, title: "Delete export", className: "rounded-full border border-red-400/40 bg-red-500/10 px-3 py-1 text-xs font-semibold text-red-100 hover:bg-red-500/20", children: "Delete" }))] })] }, d.presetId))) })] }))] }));
}
function Stat({ label, value }) {
    return (_jsxs("div", { className: "rounded-lg border border-white/10 bg-slate-950/60 p-2", children: [_jsx("p", { className: "text-[10px] uppercase tracking-[0.18em] text-slate-500", children: label }), _jsx("p", { className: "mt-1 text-xs font-semibold text-slate-100", children: value })] }));
}
